### ISSUE TITLE
Rainfall Triggered Landslide

### ISSUE THREAD

**Issue by VikashPR** [VikashPR/18CSE301J-Projects#221]
@SohamGhosh3101 please mention your team-members GitHub for featuring in contributors list

#210

**Comment by SohamGhosh3101** [comment]
Surely!

https://github.com/basit9958
https://github.com/Prateek-sn-coder
https://github.com/A-Tanz
https://github.com/suyashjoshi404
https://github.com/AlpacaMan14
https://github.com/SohamGhosh3101

**Comment by VikashPR** [comment]
> Surely! https://github.com/basit9958 https://github.com/Prateek-sn-coder https://github.com/A-Tanz https://github.com/suyashjoshi404 https://github.com/AlpacaMan14 https://github.com/SohamGhosh3101
> […](#)

@SohamGhosh3101 much appreciated, thank you for quick reply

**Comment by VikashPR** [comment]
@all-contributors
please add @basit9958 for content, example.
please add @Prateek-sn-coder for content, example.
please add @A-Tanz for content, example.
please add @suyashjoshi404 for content, example. 
please add @AlpacaMan14 for content, example. 
please add @SohamGhosh3101 for content, example.

**Comment by SohamGhosh3101** [comment]
My pleasure!
Thank you for the good work!

**Comment by VikashPR** [comment]
> My pleasure! Thank you for the good work!
> […](#)

Your are most welcome Soham Ghosh, you and your friends contribution to the our biggest Open-Source repository will always be welcomed.

**Comment by VikashPR** [comment]
@all-contributors
please add @A-Tanz for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @suyashjoshi404 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @AlpacaMan14 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add @SohamGhosh3101 for content, example.

**Comment by VikashPR** [comment]
@all-contributors please add  @Prateek-sn-coder for content, example.

**Comment by VikashPR** [comment]
@SohamGhosh3101 please confirm if all your friends are added in the contributors list. If you have any issues feel free to reopen the issues 🦋

**Comment by SohamGhosh3101** [comment]
> @SohamGhosh3101 please confirm weather all your friends are added in the contributors list. If you have any issues feel free to reopen the issues 🦋

No issues, everyone is added. Thank you 👍
